# .github/actions/setup-mvn/action.yml
name: Override Maven settings if MAVEN_SETTINGS is defined
description: Creates Maven settings.xml from environment
runs:
  using: "composite"
  steps:
    - name: Setup Maven settings
      run: |
        if [ -n "${MAVEN_SETTINGS}" ]; then
          mkdir -p /root/.m2
          echo "$MAVEN_SETTINGS" > /root/.m2/settings.xml
          echo "✅ /root/.m2/settings.xml overridden"
        else
          echo "ℹ️ MAVEN_SETTINGS not set, skipping override"
        fi
        if [ -n "${MAVEN_SETTINGS_SECURITY}" ]; then
          mkdir -p /root/.m2
          echo "$MAVEN_SETTINGS_SECURITY" > /root/.m2/settings-security.xml
          echo "✅ /root/.m2/settings-security.xml overridden"
        else
          echo "ℹ️ MAVEN_SETTINGS_SECURITY not set, skipping override"
        fi
      shell: bash
      env:
        MAVEN_SETTINGS: ${{ env.MAVEN_SETTINGS }}
        MAVEN_SETTINGS_SECURITY: ${{ env.MAVEN_SETTINGS_SECURITY }}
